--ejercicio de unn corso r de tipo implicito
--LO USAREMOS CON LA TABLA PELIVCULA
SET SERVEROUTPUT ON;

DECLARE 
VALOR VARCHAR2(50);
BEGIN
SELECT TITULO INTO VALOR FROM PELICULA WHERE ID_PELICULA=1;
DBMS_OUTPUT.PUT_LINE('EL TITULO DE LA PELICULA ES : '||VALOR);
END;
/


-- AHORA VERMEOS IUNJ CURSOR EXPLICITO CON LA LMISMA TABLA Y EL 
--EJEMPLO MUY PARECIDO 

DECLARE 
CURSOR CUR_1 IS SELECT *FROM PELICULA;
BEGIN
FOR REC IN CUR_1 LOOP 
DBMS_OUTPUT.PUT_LINE('LA PELICULA ES : '||REC.TITULO );
END LOOP;
END;
/